### ISSUE TITLE
Third party language support beyond C#, Python and R

### ISSUE THREAD

**Issue by masters3d** [Azure/usql#132]
Hi, 

What is the  `Extension.MyLanguage` path to support other languages? Let's say I have a Java reducer that I want to import, Can I add support myself for this? 

I am new to U-SQL and this is the first question that came to mind. 
Is the below support hard coded into the language? Are there plans to provide a way for me to add support to other languages like Lua or Julia etc. 
`REFERENCE ASSEMBLY [ExtPython];`

Thanks!

**Comment by MikeRys** [comment]
The ExtPython/ExtR U-SQL Assemblies include the Python and R runtimes respectively as part of the assembly (note that this is a U-SQL concept and is named the same for all languages :)). So if you can deploy a JVM runtime within the resource constraints of a vertex, you could do a similar approach. There is a //build2017 video where I show the basics, although at the time I only demo'ed it with local run since there were some issues with the JVM deployment into the cluster. Having said that, ...

**Comment by MikeRys** [comment]
... Having said that, we are currently working on providing a much more native integration of the UDO model for Python and JVM/Java. I gave some demos at //build this year that shows the experience, including running a Hive JSON serde from within a U-SQL EXTRACT statement. The Python capability is in private preview now, and the JVM/Java will be later this summer. Feel free to send email (usql at microsoft dot com), if you are interested in signing up for the previews - once it is available in the JVM case.

**Comment by masters3d** [comment]
1) So I am gathering that right now any language support needs to be implemented by the U-SQL team? 
2) Or are you saying that as long as I am able to embed the runtime in an "assembly" then it is possible for me to add this support myself?
3) Is there a limitation to only embedded runtimes? Is there a way to run as an out of process in the host version of the runtime on ADL? (New to ADL too :)

**Comment by MikeRys** [comment]
What I am basically saying is that you can do #2. There are some limits on the size of resources that you can deploy (I think a single resource file cannot be larger than 400MB and you have a total limit for all resources in a job of about 3GB). You can invoke executables in a separate process as long as they run within the boundary of the container (i.e., you cannot make any network calls).

I am also saying that we are adding some common languages right now more natively (Python and Java/JVM).

**Comment by masters3d** [comment]
oh very nice! Thank you for all the info. I’m looking forward to using it.
