### ISSUE TITLE
FileCopyUDO example not working

### ISSUE THREAD

**Issue by ewok2030** [Azure/usql#137]
I'm having trouble using the [FileCopyUDOs](https://github.com/Azure/usql/blob/master/Examples/FileCopyUDOs/FileCopyUDOs/Script.usql.cs) example. 

I pasted the code from above into my own project and ran the example script. I am receiving the following error:

` VertexFailedTooManyDueToSystemError_Runtime: Vertex failed too many times due to Runtime system error.`

With a sub-error of:

`E_RUNTIME_SYSTEM_INTERNALISSUE: An internal error has been reported 'Assertion failed: 'localStartOffset < localEndOffset' at ScopeEngine::DryadChannel::ValidateOffsets(2191),<not supplied>'`

Component: `RUNTIME`
Message: `An internal error has been reported 'Assertion failed: 'localStartOffset < localEndOffset' at ScopeEngine::DryadChannel::ValidateOffsets(2191),<not supplied>'`

Does anybody have any advice?

**Comment by MKadaner** [comment]
This does not feel good. Could you please open support ticket (an IcM)? Severity 4 would be appropriate. We need it to have formal permission to access your script and data. Please provide failed job link and state clearly that we have your consent to see the data.

**Comment by ewok2030** [comment]
It appears to have been an issue with the file I was using. I used `/dev/random` to generate some garbage data, but perhaps the file was invalid. 

I downloaded an ubuntu ISO and that worked just fine.
