### ISSUE TITLE
Strongly Typed IProcessor

### ISSUE THREAD

**Issue by isaacabraham** [Azure/usql#16]
Any possibility of having a strongly typed version of ```IProcessor``` i.e. ```IProcessor<TInput, TOutput>``` which would then have ```Process(row:IRow<TInput>) : output:IRow<TOutput>``` - this is basically just the prototypical map function in many collection libraries (or select in LINQ).

In the current implementation, things are all stringly typed - so developers will either just put up with that and risk runtime errors, or end up writing wrapper classes around the input IRow and output IUpdateableRow in order to get some strong typing into that.

**Comment by MikeRys** [comment]
Thanks for the feedback Isaac. Please note that we currently do not have a row type per se in the type system. However we are having a STRUCT type on the backlog and it could make sense to use it to type the UDOs with that type to mimic the row structures.

**Comment by isaacabraham** [comment]
Is this closed as "will not fix" or "fixed" or "by design" or... :-)

**Comment by MikeRys** [comment]
I am not sure why Saveen closed it. I see it as, but onto the backlog and pending further feedback and investigation :)
