### ISSUE TITLE
Could not load type 'ScopeRuntime.ScopeDynamicPartitionedOutputCollector' error in local run

### ISSUE THREAD

**Issue by helloyesthisisdave** [Azure/usql#161]
Currently getting the following error when trying to run locally in both VS2019 Enterprise version 16.6.1 and VS2019 Enterprise Preview 2.0 version 16.7.0, using the Azure Data Lake and Stream Analytics Tools version 2.4.6000.1:

>error E_CQO_SYSTEM_INTERNAL_ERROR: Could not load type 'ScopeRuntime.ScopeDynamicPartitionedOutputCollector' from assembly 'ScopeRuntime, Version=1.0.0.0, Culture=neutral, PublicKeyToken=bf257442a062f16a'.

As the error suggests, I am trying to OUPUT to a partitioned path.

This has not been a problem before, is there a fix/workaround available?

**Comment by edelweissno1** [comment]
> Currently getting the following error when trying to run locally in both VS2019 Enterprise version 16.6.1 and VS2019 Enterprise Preview 2.0 version 16.7.0, using the Azure Data Lake and Stream Analytics Tools version 2.4.6000.1:
> 
> > error E_CQO_SYSTEM_INTERNAL_ERROR: Could not load type 'ScopeRuntime.ScopeDynamicPartitionedOutputCollector' from assembly 'ScopeRuntime, Version=1.0.0.0, Culture=neutral, PublicKeyToken=bf257442a062f16a'.
> 
> As the error suggests, I am trying to OUPUT to a partitioned path.
> 
> This has not been a problem before, is there a fix/workaround available?

Hi, I am PM of Scope team, we noticed this issue from Marketplace, and trying to reproduce and fix this issue. 
We will be appreciate if you can send us more detail to this email account: cosctcs at microsoft dot com, that would be very helpful.
Thanks.

**Comment by edelweissno1** [comment]
> I got the same error with VS2019 Professional version 16.6.1 using the Azure Data Lake and Stream Analytics Tools version 2.4.6000.0

Hi, please contact us to this email account about this issue: cosctcs at microsoft dot com.
Thank you!

**Comment by xujxu** [comment]
Hi, This has been fixed in latest extension. Please try it out with extension update.
