### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by PeterAronZentai** [Azure/usql#162]
There has been no commits for over a year, not even to bring this up to .NET 4.8.
Should I be considering this tool at all for a new system?

**Comment by kszicsillag** [comment]
The whole ADLA+USQL story looks like dead (apart from occasional VS Extension updates). No official statement I could find though.
Unoffficial: [https://www.red-gate.com/simple-talk/blogs/microsoft-data-platform-2020/](https://www.red-gate.com/simple-talk/blogs/microsoft-data-platform-2020/)

**Comment by xujxu** [comment]
Hi, the Azure Data Lake Analytics service is not dead yet. It is still running with certain support by MSFT. Please refer to the Azure Doc for information: https://docs.microsoft.com/en-us/azure/data-lake-analytics/data-lake-analytics-whats-new .
