### ISSUE TITLE
Extracting data from multiple files 

### ISSUE THREAD

**Issue by rakeshdavanum** [Azure/usql#25]
Hi,

I am trying to use the EXTRACT USQL statement when the location pointed by FROM has multiple files. It works when I have a single file and I am explicitly specify the filename in the path. But in my use case it is not guaranteed that the filename will be the same everytime or the folder can have multiple files.

In the below statement I have tried using FROM "/dimensiondata/carrier/", 	FROM "/dimensiondata/carrier/*" and 	FROM "/dimensiondata/carrier" but none of them worked. All 3 of them came back with error saying "File not found:".

@carrierdata =
	EXTRACT Carrier	string,
			CarrierCode	string
	FROM "/dimensiondata/carrier/"
	USING Extractors.Csv();

How would I go about reading data from multiple files using an EXTRACT statement?
Appreciate your help on this.

Thanks & Regards,
Rakesh

**Comment by michaelamadi** [comment]
Hi Rakesh,

You'll need to use a file set pattern as described here: https://msdn.microsoft.com/en-us/library/azure/mt621294.aspx

In your specific case you could use the following if you don't need access to the file name values in the row set returned:
@carrierdata =
EXTRACT Carrier string,
CarrierCode string
FROM "/dimensiondata/carrier/{*}"
USING Extractors.Csv();

If you do need access to the file name values, then you can map the wild card to a virtual column like this: 
@carrierdata =
EXTRACT Carrier string,
CarrierCode string,
FileName string 
FROM "/dimensiondata/carrier/{FileName:*}"
USING Extractors.Csv();

Please note that the virtual column, in this case ‘FileName’, must also appear in the column definition list of the EXTRACT expression.

Regards, 

Michael

**Comment by rakeshdavanum** [comment]
Hi Michael,

Thank you so much! That worked :) Being able to extract the FileName was very useful too.

Thanks & Regards,
Rakesh
