### ISSUE TITLE
Value formatter for data partitioned by hour

### ISSUE THREAD

**Issue by hughwasos** [Azure/usql#26]
When specifying a data set which is partitioned by hour I expect the format specifier "hh" to represent the hour on a 12 hour clock, and the format specifier "HH" to represent the hour on a 24 hour clock. This expectation is based on [Custom Date and Time Format Strings in .net documentation](https://msdn.microsoft.com/en-us/library/8kb3ddd4%28v=vs.110%29.aspx).

When using the format specifier "HH" I get an error `Internal error! Invalid Virtual Column: Cannot find value formatter 'HH' for type 'DateTime' of column 'logfile_timestamp'`

When using the format specifier "hh" I get the hour from a 24 hour clock.

**Comment by MikeRys** [comment]
Thanks Hugh... I will check and potentially adjust this (will be a breaking change though, if we switch hh to 12 hour clock). 
Note that we do not support am/pm indication though. So switching hh to 12 hour clock may not be feasible.

But I think it makes sense to support at least both formats.

**Comment by hughwasos** [comment]
Thanks Mike. 

In my case, I want to use the 24 hour format and I am able to achieve this, but I was confused by the syntax. I don't have a use case which requires 12 hour format or am/pm indication.

**Comment by MikeRys** [comment]
Just a quick update: We are going to change the hour format in two steps from hh to HH:

First step/release will be that we support both. 
Second step/release about a month later will remove hh.

Our release notes will call it out when it will happen. Thanks for reporting :)

**Comment by MikeRys** [comment]
This change has been released some time ago (cleaning up open issues).
