### ISSUE TITLE
Trying to access assembly from USQL script in portal

### ISSUE THREAD

**Issue by nitin16** [Azure/usql#34]
Hi, 

I am trying to parse Json data file using Json formatter. 
I have following on top of my script. 
REFERENCE ASSEMBLY [Newtonsoft.Json];
REFERENCE ASSEMBLY [Microsoft.Analytics.Samples.Formats]; 

But I keep getting error saying Assembly 'master.[Newtonsoft.Json]' does not exist.

Do I need to upload these assemblies to data lake store ? if yes where ?

Thanks, 
Nitin

**Comment by mwinkle** [comment]
As a first step, you need to register the assemblies with the catalog.  You can do this from PowerShell, Visual Studio, or the cross platform CLI.

If you'd like to see this in the portal, please file a feature request at feedback.azure.com

**Comment by nitin16** [comment]
This worked. Thanks.

**Comment by nitin16** [comment]
I did this through visual studio and worked great. Do you have any example of powershell script to do the same ?

**Comment by matt1883** [comment]
When you use Visual Studio to register an assembly with your catalog, Visual Studio submits a U-SQL script to perform the action.

The script has the following contents, where the large hex number is the hex-encoded contents of the assembly that you're registering.

```
USE DATABASE [master];
CREATE ASSEMBLY [MyAssembly] FROM 0x4D5A90000300000004000
```

To submit a job through Azure PowerShell or Azure CLI, see these articles:

- [Azure PowerShell](https://azure.microsoft.com/en-us/documentation/articles/data-lake-analytics-get-started-powershell/#submit-data-lake-analytics-jobs)
- [Azure CLI](https://azure.microsoft.com/en-us/documentation/articles/data-lake-analytics-get-started-cli/#submit-data-lake-analytics-jobs)

To get the hex-encoded contents of your assembly using Azure PowerShell, you can do the following:

```
$bytes = Get-Content myAssembly.dll -Encoding Byte
[System.BitConverter]::ToString($bytes).Replace("-","")
```

If you'd rather upload your assembly to Data Lake Store or Azure Storage and reference it when registering the assembly, you can do this as well. Simply replace the binary value with an adl:// or wasb:// path to the assembly file that you'd like to register.

The details of this U-SQL script can be found [here](https://msdn.microsoft.com/en-us/library/azure/mt621364.aspx).

**Comment by ksureshhpk** [comment]
But assembly creation not working with windows server 2019, its throwing exception like cannot create assembly since its system assembly. Anybody faced this issue?
