### ISSUE TITLE
How to process one row at a time in USQL

### ISSUE THREAD

**Issue by sarath-rachuri** [Azure/usql#35]
How can we process one row of structured data at a time using USQL. Is it possible to use something like cursor in SQL that opens on a result set and allows processing the result set one row at a time.

**Comment by MikeRys** [comment]
Dear Sarath. The whole purpose of U-SQL is to give you set-based declarative processing so we can optimize and scale it out. Cursors would be the death of that.

You can do however declarative row-level processing by:

1. Use the standard SELECT FROM WHERE with expressions in the select clause, or
2. Write a custom processor UDO and invoke it with PROCESS (see https://github.com/Azure/usql/blob/master/Examples/AmbulanceDemos/AmbulanceDemos/3-Ambulance-User%20Code/3.2-Ambulance-UseUDOs.usql for some examples)

Most of the processing you can do declaratively as well. If you need to do procedural data flow (e.g., a while loop), then you should first think of doing it declaratively instead. And if that does not work, I would suggest to break your script into parts and use an orchestration component such as Azure Data Factory or write your Powershell scripts to do the procedural orchestration.

**Comment by sarath-rachuri** [comment]
Thanks Mike. With the help of the custom processor UDO and by invoking the UDO with PROCESS, I'm able to do row-level processing.
