### ISSUE TITLE
Sample User-Defined Aggregator

### ISSUE THREAD

**Issue by edevil** [Azure/usql#37]
It would be nice to have a sample of code that implements Microsoft.Analytics.Interfaces.IAggregate in order to provide and use a user defined aggregator.

**Comment by rukmanig** [comment]
Hi @edevil  - you can find an example that I published last month in https://github.com/Azure/usql/tree/master/Examples/Extensibility-Simple-Examples/Extensibility-Simple-Examples.

It has an example of using a user defined aggregate for calculating the balance based on the type of transaction (add when its credit and subtract when its debit). Please let me know if you have any specific questions. 

Look for the SampleAggregate class in the following file for source code. https://github.com/Azure/usql/blob/master/Examples/Extensibility-Simple-Examples/Extensibility-Simple-Examples/Script.usql.cs
