### ISSUE TITLE
Schedule usql jobs

### ISSUE THREAD

**Issue by nitin16** [Azure/usql#38]
Is there any way I can automate U-SQL jobs and run them on some schedule?

**Comment by nitin16** [comment]
Currently I am trying to use powershell script and trying to run through Run book. Please let me know if there is better way.

**Comment by saveenr** [comment]
Although there are several options, we recommend Azure Data Factory for scheduling the regular submission of U-SQL jobs

**Comment by nitin16** [comment]
Thanks. I have started using those and looks like I could make it work for my scenario.
