### ISSUE TITLE
Building recursive queries

### ISSUE THREAD

**Issue by TEitelberg** [Azure/usql#41]
Hi,

I have to build the transitive closure of a result set. Usually I would use recursive CTE or something like the Floyd–Warshall algorithm in C#.
Currently I find no approach, how I could solve this in U-SQL. Are there existing approaches which I have overlooked?

Regards,

Tillmann

**Comment by MikeRys** [comment]
U-SQL does not provide for fix-point recursion since that is not that easily implemented with the current a priori scale-out plan generation. Best is to anticipate the approximate max level of recursion and then explicitly repeat the statements.

**Comment by MikeRys** [comment]
Since we had no more comments I am closing this issue. If you want to request a feature, please file it at http://aka.ms/adlfeedback.
