### ISSUE TITLE
String size exceeds the maximum allowed size of 131072 in U-SQL script

### ISSUE THREAD

**Issue by SaiPrasannaAnnamalai** [Azure/usql#46]
Hello,
I am hitting the error of string data type size limitation of 128KB during extract phase.

I tried the option of Extractors.Tsv(silent:true) to omit the corresponding rows which does not fit the 128KB but that doesn’t seem to solve the problem.

I do not want to parse using custom extractors and want to consume the entire line and then process if necessary.

**Code snippet:**
`@eventLogs =
    EXTRACT Event string
    FROM @path
    USING Extractors.Tsv(silent:true);
`

**Error:**
MESSAGE: String size 215710 exceeds the maximum allowed size of 131072

Questions:
• Is there a way to store larger literals than 128KB during extraction?
• If not is there a way to omit those lines instead of run-time failure?

**Comment by MikeRys** [comment]
The only way to work around this limitation at this point is to write a custom extractor. However, you will have to expose the data not as a string (since the U-SQL string data type's max size is 128kB) but as byte[].

Unfortunately, the built-in extractors use base64 encoding for binary values and are also limited by the string size limit. But if you use a custom extractor that just reads the byte array, you can go up to 4MB.

In general, if you need to parse your row, it is going to be probably faster, if you write your custom extractor instead of using the built-in extractor and then write another U-SQL transformation or two to parse the data (again).

**Comment by ullasm** [comment]
I have fixed the above problem by writing multiple Extract statements.

**Comment by narensoft** [comment]
Can you please share the sample with us @MikeRys  and @ullasm

**Comment by saulcruz** [comment]
A workaround example would be very nice :)

**Comment by MikeRys** [comment]
Sorry for the late reply. I currently have a version of the JSON Extractor at that shows how I use byte[] to work around the limitation: https://github.com/Azure/usql/tree/mrys-json

**Comment by kszicsillag** [comment]
Hi, we have created a tweaked version of @MikeRys' [extractor](https://github.com/Azure/usql/blob/mrys-json/Examples/DataFormats/Microsoft.Analytics.Samples.Formats/Json/JsonExtractor.cs):
- disabled the formatting of JSON outputs. This can reduce the size of the extracted JSON by more than 50%
- configurable byte array column assigning mode. It can assign to byte array column by converting the corresponding JSON fragment in the following ways:
  - **Built-in extractor mode** deserializes the JSON fragment to a byte array. The format of the fragment needs to be supported by the [JSON.NET's ToObject method](https://www.newtonsoft.com/json/help/html/M_Newtonsoft_Json_Linq_JToken_ToObject.htm). This mode is the same as the original `JsonExtractor` has.
  - **Mrys-json-branch extractor mode** assigns the byte array representation of the fragment string. It uses UTF-8 encoding to convert to string to byte array.  This mode is the same as the  `JsonExtractor` on the mrys-json branch has.
  - **Compressed mode** the same as above, but the byte array gets GZip-compressed before assigning. This comes in handy if you have longer lines than 4 MB.
- it can silently skip malformed JSON objects
- users can specify the maximum number of JSON objects to parse
- upgraded dependency JSON.NET to v11, that brings enhanced JSONPath support [among others](https://github.com/JamesNK/Newtonsoft.Json/releases/tag/11.0.1)
- added some unit tests :)

Then we created `MultilineJsonExtractor` (MJE) builds upon these features and adds the capability to process the input line-by-line in parallel.

These extractors live [in this forked repo](https://github.com/kszicsillag/usql).
[Documentation](https://github.com/kszicsillag/usql/blob/jsontweaks/Examples/DataFormats/Microsoft.Analytics.Samples.Formats/readme.md)

Hope it helps.

**Comment by zmihaylov** [comment]
Hello when trying to use @MikeRys JsonExtractor I get:

Execution failed with error '1_SV1_Extract_Split Error : '{"diagnosticCode":195887152,"severity":"Error","component":"RUNTIME","source":"User","errorId":"E_RUNTIME_USER_UNHANDLED_EXCEPTION_FROM_USER_CODE","message":"An unhandled exception from user code has been reported when invoking the method 'Extract' on the user type 'Microsoft.Analytics.Samples.Formats.Json.JsonExtractor'","description":"Unhandled exception from user code: \"Additional text encountered after finished reading JSON content: {. Path '', line 2, position 0.\
The details includes more information including any inner exceptions and the stack trace where the exception was raised.","resolution":"Make sure the bug in the user code is fixed.","helpLink":"","details":"==== Caught exception Newtonsoft.Json.JsonReaderException
   at Newtonsoft.Json.JsonTextReader.Read()
   at Microsoft.Analytics.Samples.Formats.Json.JsonExtractor.<Extract>d__2.MoveNext()  
   at ScopeEngine.SqlIpExtractor<ScopeEngine::CosmosInput,Extract_0_Data0>.GetNextRow(SqlIpExtractor<ScopeEngine::CosmosInput\\,Extract_0_Data0>* , Extract_0_Data0* output) in iot\\sdsdataanalysis\\sdsdataanalysis\\bin\\debug\\sdsanalysis\\sdsanalysis.scopeworkdir\\sqlmanaged.h:line 1937","internalDiagnostics":""}

any suggestions?

**Comment by MikeRys** [comment]
This is most likely caused by your data containing additional data after the JSON document. Can you load the document with a JSON parser and make sure it is indeed a fully valid JSON document (and not a JSON doc with additional data)?

Best regards
Michael

**Comment by zmihaylov** [comment]
@MikeRys thank you for the quick response. The problem was that the json file, had the json objects not in an array separated by comma, like in the summary you have provided, but just one after another with a new line delimiter. But nevertheless thank you once again for the quick response.

**Comment by MikeRys** [comment]
You are welcome. So it was not a single JSON document but a sequence of JSON documents that NewtonSoft.JSON does not know how to process.

**Comment by anbudhanush** [comment]
Hi Mike, 
Big thank  you for this piece. It is a life saver. 
Is it mandatory to have the start the document with "["  and end with "]". Sometimes I have to churn  bigdata sets of json through this extractor and it is bit of work to add these brackets in those massive  files.  I do it with emeditor.
