### ISSUE TITLE
Feature Request - Client-side Parsing

### ISSUE THREAD

**Issue by chadequate** [Azure/usql#47]
Long time reader, first time submitting an issue on GitHub, so I apologize if this isn't the right place for this or if this feature has already been requested. 

Pretty much just what it says in the title - it would be nice if, from Visual Studio, U-SQL queries could be parsed/checked for minor/common syntactical issues before submission to the server. It would be a huge time saver.

**Comment by yorek** [comment]
Wouldn't using the "local" deployment do the trick?

**Comment by chadequate** [comment]
You're right, I'm dumb. I somehow ignored that option, I think because I got an error trying to use it early on. Thanks!
