### ISSUE TITLE
Sample ICombiner

### ISSUE THREAD

**Issue by RemekH** [Azure/usql#53]
Would be possible to add some example showing how to make custom JOIN using ICombiner?
E.g. JOIN two data sets using BETWEEN or x>=z && y<=z

**Comment by MikeRys** [comment]
Hi Remek.... I don't think that a custom Combiner would be a great example for a BETWEEN scenario. That you should probably express as a CROSS JOIN with the BETWEEN in the WHERE clause.

Writing example Combiners is on our backlog though, although it would have to be one that shows a good use case :).

**Comment by RemekH** [comment]
Hi Mike,

I was looking for any example not necessary related to BETWEEN. I agree with you that in most cases CROSS APPLY would be better solution then COMBINE.
My first approach was to used CROSS APPLY, but it took 25min to process, then when I eventually figure out how to use COMBINE it took only 5min.
So I guess there are cases when COMBINE come handy when you need to do JOIN BETWEEN

**Comment by MikeRys** [comment]
I assume you mean a CROSS JOIN? :) And yes, custom Combiners can be more efficient than the generic CROSS JOIN/WHERE. If you feel yours is a good example and you are willing to share it, please let me know and I can add it.

**Comment by RemekH** [comment]
Yes, I meant CROSS JOIN. I’m working on article to explain how to use COMBINE. I will let you know when ready so you can decide if it’s worth to add it as example and if so I will send you all source codes

**Comment by MikeRys** [comment]
Thanks. Looking forward to the example!

**Comment by RemekH** [comment]
Hi Mike, 
Here is link to the post I mentioned: [http://remekh.blogspot.com/2016/08/azure-data-lake-analytics-process-web.html](http://remekh.blogspot.com/2016/08/azure-data-lake-analytics-process-web.html )

**Comment by MikeRys** [comment]
Thanks I already tweeted it out :).

**Comment by MikeRys** [comment]
We now have the U-SQL C# Programmability guide with samples for all UDOs at https://docs.microsoft.com/en-us/azure/data-lake-analytics/data-lake-analytics-u-sql-programmability-guide.
