### ISSUE TITLE
A commit request is outside of a reservation size. A row is too big.

### ISSUE THREAD

**Issue by bveerendrakumar** [Azure/usql#54]
Hi,

I am getting following error while processing a file.

E_RUNTIME_USER_ROWTOOBIG
MESSAGE
A commit request is outside of a reservation size. A row is too big.

Input is a Json file and we have custom extractor to parse the file. What could be the issue? We don't have enough details to debug.

**Comment by rukmanig** [comment]
Can you please share your U-SQL code and also advise on the size of your input file?

**Comment by MikeRys** [comment]
This issue looks abandoned. Closing it.
