### ISSUE TITLE
Generating rows from C# without extractor

### ISSUE THREAD

**Issue by charlieamer** [Azure/usql#62]
Hello all.

I was trying to create a range of numbers (i.e. 1,2,3,4,5,... each number in new row), I found it rather hard in SQL language, so I decided to do it in C#. The only problem was, I didn't know how to produce results back to USQL. Right now I am using extractor to do the job
```sql
@loop =
    EXTRACT i int
    FROM ""
    USING new ForLoopExtractor(0, 10);
```
```c#
    public class ForLoopExtractor : IExtractor
    {
        int from, to;
        public ForLoopExtractor(int from, int to)
        {
            this.from = from;
            this.to = to;
        }
        public override IEnumerable<IRow> Extract(IUnstructuredReader input, IUpdatableRow output)
        {
            for (int i=this.from; i<this.to; i++)
            {
                output.Set<int>(0, i);
                yield return output.AsReadOnly();
            }
        }
    }
```

Is there a more convenient way of doing this ? And also, do you plan on improving language itself to allow this ?

**Comment by edtriou** [comment]
Amer,

For generating constant rows:
The simpler approach would be to leverage SELECT … VALUES
https://msdn.microsoft.com/en-us/library/azure/mt621292.aspx

For generating dynamic rows:
UDO(s), such as the extractor are plenty powerful enough for that scenario.

Hope that helps
Ed

**Comment by charlieamer** [comment]
Yes, there are pros and cons of each possibility, but none of them is perfect. For example, using extractor requires a file in system, and it gets opened, wasting some of resources. Using UDO is only applicable where I already have a lot of rows and then process them, **please correct me if I am wrong here** (I actually want to produce rows out of nothing). As of now, the best solution is to generate range of numbers using extractor.

**Comment by edtriou** [comment]
Ø  For example, using extractor requires a file in system, and it gets opened, wasting some of resources

Extractor is just one of the (6) UDO(s).
(4) of the UDO(s) operate exclusively on rowsets (not files).

For example:

1.       Use SELECT … VALUES to get at least a 1 row rowset.

2.       Followed by CROSS APPLY of a custom applier (ie: USING <your applier UDO>)

That will allow you to explode that row into N.
Your applier can be a data generator.

Hope that helps
Ed

**Comment by MikeRys** [comment]
Ed's answer is the best way to create data generators without the need to use EXTRACTORS or files.

I am closing this comment. If you want to add to it, please feel free to reopen.
