### ISSUE TITLE
Query Execution AVG

### ISSUE THREAD

**Issue by rloski** [Azure/usql#72]
I am using USQL to query my PUMS population files.  I am using the AVG function. 

@sum = SELECT St, AVG(Adjinc) AS AvgIncome
FROM @tbl 
GROUP BY St;

The USQL engine appears to pass every rows' St and Adjinc values to the final vertex which then aggregates the results.

However, you could much more efficiently create hash tables in each vertex, storing the SUM Adjinc and COUNT of rows.  Then when you merge the hash tables, you sum the Adjinc and sum the COUNT of rows.  You then divide the Sum of Adjinc by the COUNT of rows to get the Average.

**Comment by MikeRys** [comment]
Thanks for the suggestion. I will see what my optimizer team can do :). I close the comment for now but feel free to reopen if you want to add more information.
