### ISSUE TITLE
Could not load file or assembly 'ScopeEngineManaged.dll' or one of its dependencies - Using the SDK

### ISSUE THREAD

**Issue by guruper** [Azure/usql#73]
I get this error when I try to compile using the Local Run Assembly directly:

string USQLRootPath = @"C:\USQLLocalRunSDK\DataRoot";
string ScriptPath = @"C:\USQLLocalRunSDK\Scripts\USQLScripts";
string ScriptName = "SimpleTest.usql";

Configuration USQLConfig = new Configuration(USQLRootPath);
USQLConfig.CppSDK = @"C:\USQLLocalRunSDK\CppSDK";
USQLConfig.WorkingDirectory = @"C:\USQLLocalRunSDK\Scripts\ScopeWorkDir";

LocalCompiler USQLCompile = new LocalCompiler(USQLConfig):

In the Compile Result I can find the following Error: "Could not load file or assembly 'ScopeEngineManaged.dll' or one of its dependencies".

I have no problem compiling the same script using localrunhelper.exe like this:

C:\USQLLocalRunSDK\LocalRunHelper.exe "compile" -Script "C:\USQLLocalRunSDK\Scripts\USQLScripts\SimpleTest.usql" -DataRoot "C:\USQLLocalRunSDK\DataRoot" -CppSDK "C:\USQLLocalRunSDK\CppSDK"

Is there something I'm doing wrong in using the Assemblies directly? The VS 2015 project is targeted for x64.

**Comment by yangyud-cn** [comment]
Hi,   This is a known limitation on Windows earlier than Win 10.  Could you please refer to here for the solution?
http://stackoverflow.com/questions/42250120/usql-vs-2015-internal-error-a-procedure-imported-by-scopeenginemanaged-dll#42250120

**Comment by yangyud-cn** [comment]
dup of #66 and #52

**Comment by guruper** [comment]
I'm running Windows 10, so I can't see that the solution is related. And It's working correctly then using the tools in VS 2015 and also using the localrunhelper.exe.

**Comment by melpcollins** [comment]
I am also having this issue.  I updated to 2.2.5000.0 this morning and got this error. 
I've applied all the patches above with no luck.  Windows 7.
I have both the updates described here already installed.

http://stackoverflow.com/questions/42250120/usql-vs-2015-internal-error-a-procedure-imported-by-scopeenginemanaged-dll#42250120

**Comment by jitendriyag2** [comment]
I am trying to publish the Scope Monitoring Tool using VcClient Tool in WebJob but it won't work showing the error: 
System.BadImageFormatException: Could not load file or assembly 'ScopeEngineManaged, Version=10.2.0.0, Culture=neutral, PublicKeyToken=a06e40edc83d4f79' or one of its dependencies. An attempt was made to load a program with an incorrect format.

I already added the scopeenginemanaged dll as an reference but still showing error. but in local machine it is running fine.

**Comment by kotpal** [comment]
This happened today on Windows 10. I have VS 2019 installed. 

- I used Fusion Log to get more information on why I am not able to load ScopeEngineManaged.DLL.  
- I use ProcMon to see what DLLs, Assemblies are trying to be loaded when this error occurs.

Nothing so far. 

Can someone who figured the secret sauce to get this to work, please share the information?

**Comment by kotpal** [comment]
This is really bogus. Sorry, but I don't have any other words. DLL Hell - redux.

I found **876** instances of VCRUNTIME140.DLL and **405** instances of API-MS-WIN-CRT-RUNTIME-L1-1-0.DLL on my machine - and Dependency Walker finds out that ScopeEngineManaged.DLL can't load API-MS-WIN-CRT-RUNTIME-L1-1-0.DLL

{{ Speech-less in Seattle }}

**Comment by asears** [comment]
If this is related to USQL, I was able to fix by copying Data Lake Analytics SDK CppSDK folder to c:\LocalRunSDK\CppSDK.  It can be installed via Nuget.  

https://www.nuget.org/packages/Microsoft.Azure.DataLake.USQL.SDK/

The instructions should be here, it was tricky!
https://docs.microsoft.com/en-us/azure/data-lake-analytics/data-lake-analytics-u-sql-sdk
