### ISSUE TITLE
Internal Error, and now the editor options bar is missing (submit, local/remote, DB, schema dropdown bar)

### ISSUE THREAD

**Issue by sqlaz** [Azure/usql#74]
Getting a usql internal error. Thought I'd uninstall, and reinstall the ADL Tools for VS, and now the submit, local/remote option, DB nor schema dropdowns are no longer available. Using v2.2.5000.0 on VS 2015 Enterprise.

![usql_internalerror](https://cloud.githubusercontent.com/assets/25693291/23568847/85bc150e-002a-11e7-8c8d-4d70c4273a00.JPG)

**Comment by yangyud-cn** [comment]
@sqlaz, the answers in #66 should have resolved your issues.  Please let me know if it is OK to close this issue.

Thanks,
Yu Dong

**Comment by sqlaz** [comment]
Yes, if I revert back to the older version of ADLT4VS, things are working fine - but not with the latest (v2.2.5000.0).  I suspect this might be the case going forward - since the next release of the tool is due anytime now (the prev release was on 2/8/2017).  Also, I updated to Azure SDK v3.0 (released a couple of days back, on Mar 7th, coinciding with VS 2017 release) - that didn't fix it either.  I think the safe bet is to use Windows 10, if we need the latest tool in local mode (the newer one offers multiple degrees of parallelism in local mode [upto 7, I guess] which is not available in the prev versions).  Given the limitations, understandable where things are headed. 

Thanks for your help, Yu.  Please proceed with closing this ticket.
