### ISSUE TITLE
Add custom column in output

### ISSUE THREAD

**Issue by lokesh-zende** [Azure/usql#78]
Hi,
I have a .tsv file which I can process. I want to add an extra column to the output .csv file.
That extra column will be a datetime column in the format YYYYMMDDHHMM.
Is it possible?
This is my simple query
 ```
@Result = 
EXTRACT 
            User_ID int,
            First_Name string,
            Middle_Name string,
            Last_Name string,
            Age int,
            Gender string,
            Team string,
            CurrentTime DateTime  // Is it possible to create a datetime column here like we do in sql ??
        FROM "/Users.tsv"
        USING Extractors.Tsv();
```

Any help appreciated.

Lokesh.

**Comment by lokesh-zende** [comment]
I did something like this.
Declare a variable and assign datetime value in desired format to that variable.
Then use that variable with the result received by extracting a .tsv.

```
DECLARE @Date = DateTime.Now.ToString("yyyyMMddHHmm");

@Result = 
    EXTRACT 
            User_ID int,
            First_Name string,
            Middle_Name string,
            Last_Name string,
            Age int,
            Gender string,
            Team string
        FROM "/Users.tsv"
        USING Extractors.Tsv();

@Final = SELECT *, @Date AS Date FROM @Result;

OUTPUT @Final
TO "/UsersConverted.csv"
USING Outputters.Csv();
```
            
Though it works, I would like to know if there are any other ways to achieve this.

**Comment by MikeRys** [comment]
If you want to add a single value to all the rows, your approach is probably the best one. You could write a custom extractor but that is too much overhead. If you have more values that you want to add depending on a value in the file, create a constant table (with SELECT FROM VALUES) and join it with the result of the extraction.
