### ISSUE TITLE
Output column names of a table using USQL, Csv Outputter

### ISSUE THREAD

**Issue by Kishorebv** [Azure/usql#9]
I have a rowset that is created from a ADL database table. When I use Output with Csv Outputter, it is outputting the rows with out the column headers, Is it possible to get the column names outputted as first row?

**Comment by tomkerkhove** [comment]
I'd love this as well!

**Comment by MikeRys** [comment]
We have this on our backlog. And now you can upvote it on https://feedback.azure.com/forums/327234-azure-data-lake/suggestions/10635558-generate-heading-rows-using-the-built-in-adla-outp. 

Current workarounds are:

1. @ res = SELECT * FROM VALUES (1, "col1", ... ) AS H(headerline, col1, ...) UNION ALL 
    SELECT 0 AS headerline, col1 as string AS col1, ... FROM @data;
    OUTPUT @res TO "/output/result.csv" ORDER BY headerline DESC USING Outputters.Csv();

   Drawbacks are: You have to covert data to string in U-SQL, extra headerline column.

2. Write custom outputters and enforce atomicFileProcessing for the outputter.

**Comment by MikeRys** [comment]
Here is a sample outputter that outputs the header information. Note that outputting the data is left as an exercise to the reader :).

https://github.com/MicrosoftBigData/usql/tree/master/Examples/HeaderOutputter

**Comment by MikeRys** [comment]
This feature has been added. See https://github.com/Azure/AzureDataLake/blob/master/docs/Release_Notes/2016/2016_10_16/USQL_Release_Notes_2016_10_16.md#the-built-in-outputters-provide-option-to-output-column-names-as-header
