### ISSUE TITLE
Usql compilation files size

### ISSUE THREAD

**Issue by akuzhan** [Azure/usql#97]
Hi, 

size of our **__ScopeCodeGenEngine__.pdb** is 10MB to 100 MB. Is there a way to get rid of .pdb files while compiling usql scripts? 

In 3 days our data lake store consumption reached to almost 100 GB because azure data factory dumps all the compilation files to data lake store. 

Cheers!

**Comment by MikeRys** [comment]
I am not sure who is writing this. Are you referring to the files that are being created in the job directory in the /system folders? These files are part of the job retention and will allow you to do local vertex debug etc. The files for a job will expire after the job data expiration that you can set from your portal.

**Comment by akuzhan** [comment]
That is what we ended up doing. Thanks!
